# Panels
[style]Panel.StudyPanel = border: 20, 20, 20, 20
[style]Panel.CardViewPanel = arc: 16; background: $EditorPane.background; border: 10, 10, 10, 10

# Labels
[style]Label.deckTitle = font: +12 bold
[style]Label.frontTextLabel = font: +8 bold
[style]Label.backTextLabel = font: +4

# Buttons
[style]Button.standard = focusable: false
[style]Button.abortButton = hoverBorderColor: #FF4444; focusable: false

# Grade buttons
[style]Button.gradeAgain = outlineColor: #FF4444; borderWidth: 0; hoverBackground: darken(#FF4444, 15%)
[style]Button.gradeHard = outlineColor: #FFBB33; borderWidth: 0; hoverBackground: darken(#FFBB33, 15%)
[style]Button.gradeGood = outlineColor: #00C851; borderWidth: 0; hoverBackground: darken(#00C851, 15%)
[style]Button.gradeEasy = outlineColor: #33B5E5; borderWidth: 0; hoverBackground: darken(#33B5E5, 15%)